#!/bin/sh

##################################################################
#

# This script will clear the screen of contents but keep the      
#
# cursor in the same spot.                                        
#

# Written By:...........Sinucidal                                 #

# Date:.................04-08-2017                                #

# Hardware:.............SainSmart 20x4 character LCD on a         #

#			Raspberry Pi B+ running Moebius OS        #

# Restrictions:.........None. This code is open to the community  #

#			to use and modify at will. If you make it #

#			better please feel free to message me. It #

#			It should work on other Raspberry Pi OSes #

#			and similar LCDs but was only built and   #
#			tested on the hardware mentioned above.   
#

###################################################################

if [ $# -eq 0 ]; then						#  This just makessure no parameters are assigned to the command

	echo -e "01\n"						#  Then issues the clear command

else
	echo -e "Please do not use any parameters on clear.\n"

fi

exit 0
